In [1]:
import pandas as pd

## load from xlsx

In [2]:
df_xlsx = pd.read_excel(io='../datasets/02.code.xlsx')
df_xlsx

      Unnamed: 0       cd      nm   gb
0              0  A060310      3S  701
1              1  A095570  AJ네트웍스  701
2              2  A006840   AK홀딩스  701
3              3  A054620  APS홀딩스  701
4              4  A265520   AP시스템  701
...          ...      ...     ...  ...
2561        2561  A189980  흥국에프엔비  701
2562        2562  A000540    흥국화재  701
2563        2563  A003280    흥아해운  701
2564        2564  A037440      희림  701
2565        2565  A238490      힘스  701

[2566 rows x 4 columns]

In [3]:
df_xlsx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2566 entries, 0 to 2565
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2566 non-null   int64
 1   cd          2566 non-null   object
 2   nm          2566 non-null   object
 3   gb          2566 non-null   int64
dtypes: int64(2), object(2)
memory usage: 80.3+ KB

In [4]:
df_xlsx.describe()

        Unnamed: 0      gb
count  2566.000000  2566.0
mean   1282.500000   701.0
std     740.884719     0.0
min       0.000000   701.0
25%     641.250000   701.0
50%    1282.500000   701.0
75%    1923.750000   701.0
max    2565.000000   701.0

In [5]:
df_html = pd.read_html('https://comp.fnguide.com/SVO2/ASP/SVD_main.asp?pGB=1&gicode=A005930&cID=&MenuYn=Y&ReportGB=&NewMenuID=11&stkGb=&strResearchYN=')
df_html

[                     0                              1              2  \
 0             종가/ 전일대비                   55,600/ -500            거래량
 1         52주.최고가/ 최저가                 87,800/ 49,900       거래대금(억원)
 2  수익률(1M/ 3M/ 6M/ 1Y)  +3.93/ -13.66/ -30.15/ -24.15       외국인 보유비중
 3      시가총액(상장예정포함,억원)                        3702253         베타(1년)
 4         시가총액(보통주,억원)                        3319199            액면가
 5                  NaN                            NaN            NaN
 6      발행주식수(보통주/ 우선주)     5,969,782,550/ 822,886,700  유동주식수/비율(보통주)

                        3
 0               15277277
 1                   8536
 2                  50.91
 3                1.22766
 4                    100
 5                    NaN
 6  4,544,753,599 / 76.13  ,
   잠정실적발표예정일  예상실적(영업이익, 억원)  3개월전예상실적대비(%)  전년동기대비(%)
 0        미정          358086         -16.04     445.28,
           운용사명      보유수량     시가평가액  상장주식수내비중  운용사내비중
 0       삼성자산운용  54814.35  33710.83      0.92    3.68
 1     미래에셋자산운용  35158.15  21622.26      0.59    2.53
 2      케이비자산운용  12061.05   7417.55      0.20    2.24
 3     한국투자신탁운용   9266.52   5698.91      0.16    2.13
 4  엔에이치아문디자산운용   7572.39   4657.02      0.13    3.04
 5     교보악사자산운용   6067.79   3731.69      0.10    3.58
 6     키움투자자산운용   4915.18   3022.84      0.08    1.79
 7       신한자산운용   4635.77   2851.00      0.08    1.43
 8       신영자산운용   4386.99   2698.00      0.07    6.58
 9       한화자산운용   4089.18   2514.84      0.07    2.48,
                                항목         보통주    지분율       최종변동일
 0                   삼성생명보험(외 16인)  1198079626  20.07  2024/11/27
 1                          국민연금공단   458637667   7.68  2022/08/16
 2  BlackRock Fund Advisors(외 15인)   300391061   5.03  2019/01/28
 3                             자사주    19700000   0.33  2024/12/13
 4                             이병철      408650   0.01  2018/05/04
 5                             서병삼       70300   0.00  2018/05/04,
                  주주구분  대표주주수           보통주    지분율       최종변동일
 0    최대주주등 (본인+특별관계자)    1.0  1.198080e+09  20.07  2024/11/27
 1  10%이상주주 (본인+특별관계자)    NaN           NaN    NaN         NaN
 2   5%이상주주 (본인+특별관계자)    2.0  7.590287e+08  12.71  2022/08/16
 3   임원 (5%미만 중, 임원인자)  442.0  2.595513e+06   0.04  2024/12/06
 4    자기주식 (자사주+자사주신탁)    1.0  1.970000e+07   0.33  2024/12/13
 5              우리사주조합    NaN           NaN    NaN         NaN,
              KIS             KR           NICE
 0  관련 데이터가 없습니다.  관련 데이터가 없습니다.  관련 데이터가 없습니다.,
                 KIS                KR              NICE
 0  AAA [2004/05/25]  AAA [2004/06/17]  AAA [2004/06/01],
    투자의견   목표주가   EPS   PER  추정기관수
 0   4.0  84120  4955  11.2     25,
           구분        삼성전자   코스피 전기·전자        KOSPI
 0       시가총액  3319199.00  7219420.00  20367173.00
 1        매출액  2589355.00  5369408.00  31866484.00
 2       영업이익    65670.00    74236.00   1717309.00
 3     EPS(원)     2131.00     4446.29      4520.67
 4        PER       36.84       81.93        19.30
 5  EV/EBITDA       11.72       12.84         8.25
 6        ROE        4.14        1.95         5.02
 7      배당수익률        1.84        1.24         1.91
 8     베타(1년)        0.93        1.20         1.00,
           구분        삼성전자   코스피 전기·전자        KOSPI
 0       시가총액  3319199.00  7219420.00  20367173.00
 1        매출액  1703741.00  3462294.00  16287847.00
 2       영업이익  -115263.00  -167092.00    684751.00
 3     EPS(원)     3739.00    10115.15      4149.43
 4        PER       21.00       36.01        21.02
 5  EV/EBITDA       32.47       35.00        14.30
 6        ROE       11.70        6.39         6.10
 7      배당수익률        1.84        1.24         1.91
 8     베타(1년)        0.93        1.20         1.00,
       IFRS(연결)      Annual                                     Net Quarter  \
       IFRS(연결)     2021/12     2022/12     2023/12  2024/12(E)     2024/03
 0          매출액  2796048.00  3022314.00  2589355.00  3033219.00   719156.00
 1         영업이익   516339.00   433766.00    65670.00   358086.00    66060.00
 2   영업이익(발표기준)   516339.00   433766.00    65670.00         NaN    66060.00
 3        당기순이익   399075.00   556541.00   154871.00   348431.00    67547.00
 4      지배주주순이익   392438.00   547300.00   144734.00   336595.00    66210.00
 5     비지배주주순이익     6637.00     9241.00    10137.00         NaN     1337.00
 6         자산총계  4266212.00  4484245.00  4559060.00  4937012.00  4708998.00
 7         부채총계  1217212.00   936749.00   922281.00  1006714.00   989837.00
 8         자본총계  3048999.00  3547496.00  3636779.00  3930297.00  3719161.00
 9       지배주주지분  2962377.00  3451861.00  3532338.00  3817193.00  3623151.00
 10     비지배주주지분    86622.00    95635.00   104441.00   113105.00    96011.00
 11         자본금     8975.00     8975.00     8975.00     8979.00     8975.00
 12        부채비율       39.92       26.41       25.36       25.61       26.61
 13         유보율    32906.47    38360.25    39256.91         NaN    40268.74
 14       영업이익률       18.47       14.35        2.54       11.81        9.19
 15    지배주주순이익률       14.04       18.11        5.59       11.10        9.21
 16         ROA        9.92       12.72        3.43        7.34        5.83
 17         ROE       13.92       17.07        4.14        9.16        7.40
 18      EPS(원)     5777.00     8057.00     2131.00     4955.00      975.00
 19      BPS(원)    43611.00    50817.00    52002.00    56196.00    53339.00
 20      DPS(원)     1444.00     1444.00     1444.00     1456.00      361.00
 21         PER       13.55        6.86       36.84       11.22         NaN
 22         PBR        1.80        1.09        1.51        0.99        1.54
 23       발행주식수  5969783.00  5969783.00  5969783.00         NaN  5969783.00
 24       배당수익률        1.84        2.61        1.84         NaN        0.44


        2024/06     2024/09 2024/12(E)
 0    740683.00   790987.00  781916.00
 1    104439.00    91834.00   95378.00
 2    104439.00    91834.00        NaN
 3     98413.00   101009.00   86130.00
 4     96427.00    97815.00   82194.00
 5      1987.00     3194.00        NaN
 6   4857577.00  4913073.00        NaN
 7   1022310.00  1050260.00        NaN
 8   3835267.00  3862814.00        NaN
 9   3736696.00  3761522.00        NaN
 10    98571.00   101292.00        NaN
 11     8975.00     8975.00        NaN
 12       26.66       27.19        NaN
 13    41533.84    41810.45        NaN
 14       14.10       11.61      12.20
 15       13.02       12.37      10.51
 16        8.23        8.27       7.01
 17       10.48       10.44       8.74
 18     1420.00     1440.00    1210.00
 19    55011.00    55376.00        NaN
 20      361.00      361.00        NaN
 21         NaN         NaN        NaN
 22        1.48        1.11        NaN
 23  5969783.00  5969783.00        NaN
 24        0.44        0.59        NaN  ,
       IFRS(연결)      Annual                                                  \
       IFRS(연결)     2019/12     2020/12     2021/12     2022/12     2023/12
 0          매출액  2304009.00  2368070.00  2796048.00  3022314.00  2589355.00
 1         영업이익   277685.00   359939.00   516339.00   433766.00    65670.00
 2   영업이익(발표기준)   277685.00   359939.00   516339.00   433766.00    65670.00
 3        당기순이익   217389.00   264078.00   399075.00   556541.00   154871.00
 4      지배주주순이익   215051.00   260908.00   392438.00   547300.00   144734.00
 5     비지배주주순이익     2338.00     3170.00     6637.00     9241.00    10137.00
 6         자산총계  3525645.00  3782357.00  4266212.00  4484245.00  4559060.00
 7         부채총계   896841.00  1022877.00  1217212.00   936749.00   922281.00
 8         자본총계  2628804.00  2759480.00  3048999.00  3547496.00  3636779.00
 9       지배주주지분  2549155.00  2676703.00  2962377.00  3451861.00  3532338.00
 10     비지배주주지분    79649.00    82777.00    86622.00    95635.00   104441.00
 11         자본금     8975.00     8975.00     8975.00     8975.00     8975.00
 12        부채비율       34.12       37.07       39.92       26.41       25.36
 13         유보율    28302.40    29723.53    32906.47    38360.25    39256.91
 14       영업이익률       12.05       15.20       18.47       14.35        2.54
 15    지배주주순이익률        9.33       11.02       14.04       18.11        5.59
 16         ROA        6.28        7.23        9.92       12.72        3.43
 17         ROE        8.69        9.99       13.92       17.07        4.14
 18      EPS(원)     3166.00     3841.00     5777.00     8057.00     2131.00
 19      BPS(원)    37528.00    39406.00    43611.00    50817.00    52002.00
 20      DPS(원)     1416.00     2994.00     1444.00     1444.00     1444.00
 21         PER       17.63       21.09       13.55        6.86       36.84
 22         PBR        1.49        2.06        1.80        1.09        1.51
 23       발행주식수  5969783.00  5969783.00  5969783.00  5969783.00  5969783.00
 24       배당수익률        2.54        3.70        1.84        2.61        1.84


     2024/12(E)  2025/12(E)  2026/12(E)
 0   3033219.00  3253831.00  3433708.00
 1    358086.00   424210.00   483010.00
 2          NaN         NaN         NaN
 3    348431.00   378015.00   438387.00
 4    336595.00   365467.00   423475.00
 5          NaN         NaN         NaN
 6   4937012.00  5245181.00  5627105.00
 7   1006714.00  1043643.00  1085642.00
 8   3930297.00  4201538.00  4541462.00
 9   3817193.00  4073714.00  4396907.00
 10   113105.00   127824.00   144556.00
 11     8979.00     8976.00     8976.00
 12       25.61       24.84       23.91
 13         NaN         NaN         NaN
 14       11.81       13.04       14.07
 15       11.10       11.23       12.33
 16        7.34        7.43        8.06
 17        9.16        9.26       10.00
 18     4955.00     5380.00     6234.00
 19    56196.00    59972.00    64730.00
 20     1456.00     1401.00     1412.00
 21       11.22       10.33        8.92
 22        0.99        0.93        0.86
 23         NaN         NaN         NaN
 24         NaN         NaN         NaN  ,
       IFRS(연결) Net Quarter                                                  \
       IFRS(연결)     2023/09     2023/12     2024/03     2024/06     2024/09
 0          매출액   674047.00   677799.00   719156.00   740683.00   790987.00
 1         영업이익    24335.00    28247.00    66060.00   104439.00    91834.00
 2   영업이익(발표기준)    24335.00    28247.00    66060.00   104439.00    91834.00
 3        당기순이익    58442.00    63448.00    67547.00    98413.00   101009.00
 4      지배주주순이익    55013.00    60238.00    66210.00    96427.00    97815.00
 5     비지배주주순이익     3429.00     3209.00     1337.00     1987.00     3194.00
 6         자산총계  4544664.00  4559060.00  4708998.00  4857577.00  4913073.00
 7         부채총계   905738.00   922281.00   989837.00  1022310.00  1050260.00
 8         자본총계  3638926.00  3636779.00  3719161.00  3835267.00  3862814.00
 9       지배주주지분  3536802.00  3532338.00  3623151.00  3736696.00  3761522.00
 10     비지배주주지분   102125.00   104441.00    96011.00    98571.00   101292.00
 11         자본금     8975.00     8975.00     8975.00     8975.00     8975.00
 12        부채비율       24.89       25.36       26.61       26.66       27.19
 13         유보율    39306.65    39256.91    40268.74    41533.84    41810.45
 14       영업이익률        3.61        4.17        9.19       14.10       11.61
 15    지배주주순이익률        8.16        8.89        9.21       13.02       12.37
 16         ROA        5.18        5.58        5.83        8.23        8.27
 17         ROE        6.26        6.82        7.40       10.48       10.44
 18      EPS(원)      810.00      887.00      975.00     1420.00     1440.00
 19      BPS(원)    52068.00    52002.00    53339.00    55011.00    55376.00
 20      DPS(원)      361.00      361.00      361.00      361.00      361.00
 21         PER         NaN         NaN         NaN         NaN         NaN
 22         PBR        1.31        1.51        1.54        1.48        1.11
 23       발행주식수  5969783.00  5969783.00  5969783.00  5969783.00  5969783.00
 24       배당수익률        0.53        0.46        0.44        0.44        0.59


    2024/12(E) 2025/03(E) 2025/06(E)
 0   781916.00  786399.00  771226.00
 1    95378.00   92960.00   92024.00
 2         NaN        NaN        NaN
 3    86130.00   79740.00   79773.00
 4    82194.00   86625.00   82874.00
 5         NaN        NaN        NaN
 6         NaN        NaN        NaN
 7         NaN        NaN        NaN
 8         NaN        NaN        NaN
 9         NaN        NaN        NaN
 10        NaN        NaN        NaN
 11        NaN        NaN        NaN
 12        NaN        NaN        NaN
 13        NaN        NaN        NaN
 14      12.20      11.82      11.93
 15      10.51      11.02      10.75
 16       7.01        NaN        NaN
 17       8.74        NaN        NaN
 18    1210.00    1275.00    1220.00
 19        NaN        NaN        NaN
 20        NaN        NaN        NaN
 21        NaN        NaN        NaN
 22        NaN        NaN        NaN
 23        NaN        NaN        NaN
 24        NaN        NaN        NaN  ,
       IFRS(별도)      Annual                                    Net Quarter  \
       IFRS(별도)     2021/12     2022/12     2023/12 2024/12(E)     2024/03
 0          매출액  1997447.00  2118675.00  1703741.00        NaN   512396.00
 1         영업이익   319932.00   253193.00  -115263.00        NaN    20074.00
 2   영업이익(발표기준)   319932.00   253193.00  -115263.00        NaN    20074.00
 3        당기순이익   309710.00   254188.00   253971.00        NaN    97374.00
 4         자산총계  2511122.00  2600838.00  2968573.00        NaN  3120833.00
 5         부채총계   579185.00   506676.00   720695.00        NaN   799438.00
 6         자본총계  1931937.00  2094162.00  2247878.00        NaN  2321395.00
 7          자본금     8975.00     8975.00     8975.00        NaN     8975.00
 8         부채비율       29.98       24.19       32.06        NaN       34.44
 9          유보율    21425.43    23232.92    24945.60        NaN    25764.72
 10       영업이익률       16.02       11.95       -6.77        NaN        3.92
 11        순이익률       15.51       12.00       14.91        NaN       19.00
 12         ROA       12.88        9.94        9.12        NaN       12.79
 13         ROE       16.45       12.63       11.70        NaN       17.05
 14      EPS(원)     4559.00     3742.00     3739.00        NaN     1434.00
 15      BPS(원)    28442.00    30830.00    33093.00        NaN    34175.00
 16      DPS(원)     1444.00     1444.00     1444.00        NaN      361.00
 17         PER       17.17       14.78       21.00        NaN         NaN
 18         PBR        2.75        1.79        2.37        NaN        2.41
 19       발행주식수  5969783.00  5969783.00  5969783.00        NaN  5969783.00
 20       배당수익률        1.84        2.61        1.84        NaN        0.44


        2024/06     2024/09 2024/12(E)
 0    537341.00   558289.00        NaN
 1     72225.00    45049.00        NaN
 2     72225.00    45049.00        NaN
 3     70984.00    56946.00        NaN
 4   3176354.00  3233828.00        NaN
 5    807647.00   833108.00        NaN
 6   2368707.00  2400720.00        NaN
 7      8975.00     8975.00        NaN
 8        34.10       34.70        NaN
 9     26291.87    26648.55        NaN
 10       13.44        8.07        NaN
 11       13.21       10.20        NaN
 12        9.02        7.11        NaN
 13       12.11        9.55        NaN
 14     1045.00      838.00        NaN
 15    34872.00    35343.00        NaN
 16      361.00      361.00        NaN
 17         NaN         NaN        NaN
 18        2.34        1.74        NaN
 19  5969783.00  5969783.00        NaN
 20        0.44        0.59        NaN  ,
       IFRS(별도)      Annual                                                  \
       IFRS(별도)     2019/12     2020/12     2021/12     2022/12     2023/12
 0          매출액  1547729.00  1663112.00  1997447.00  2118675.00  1703741.00
 1         영업이익   141151.00   205190.00   319932.00   253193.00  -115263.00
 2   영업이익(발표기준)   141151.00   205190.00   319932.00   253193.00  -115263.00
 3        당기순이익   153533.00   156150.00   309710.00   254188.00   253971.00
 4         자산총계  2161809.00  2296644.00  2511122.00  2600838.00  2968573.00
 5         부채총계   383107.00   463477.00   579185.00   506676.00   720695.00
 6         자본총계  1778702.00  1833167.00  1931937.00  2094162.00  2247878.00
 7          자본금     8975.00     8975.00     8975.00     8975.00     8975.00
 8         부채비율       21.54       25.28       29.98       24.19       32.06
 9          유보율    19718.10    20324.94    21425.43    23232.92    24945.60
 10       영업이익률        9.12       12.34       16.02       11.95       -6.77
 11        순이익률        9.92        9.39       15.51       12.00       14.91
 12         ROA        7.06        7.00       12.88        9.94        9.12
 13         ROE        8.75        8.65       16.45       12.63       11.70
 14      EPS(원)     2260.00     2299.00     4559.00     3742.00     3739.00
 15      BPS(원)    26186.00    26987.00    28442.00    30830.00    33093.00
 16      DPS(원)     1416.00     2994.00     1444.00     1444.00     1444.00
 17         PER       24.69       35.24       17.17       14.78       21.00
 18         PBR        2.13        3.00        2.75        1.79        2.37
 19       발행주식수  5969783.00  5969783.00  5969783.00  5969783.00  5969783.00
 20       배당수익률        2.54        3.70        1.84        2.61        1.84


    2024/12(E) 2025/12(E) 2026/12(E)
 0         NaN        NaN        NaN
 1         NaN        NaN        NaN
 2         NaN        NaN        NaN
 3         NaN        NaN        NaN
 4         NaN        NaN        NaN
 5         NaN        NaN        NaN
 6         NaN        NaN        NaN
 7         NaN        NaN        NaN
 8         NaN        NaN        NaN
 9         NaN        NaN        NaN
 10        NaN        NaN        NaN
 11        NaN        NaN        NaN
 12        NaN        NaN        NaN
 13        NaN        NaN        NaN
 14        NaN        NaN        NaN
 15        NaN        NaN        NaN
 16        NaN        NaN        NaN
 17        NaN        NaN        NaN
 18        NaN        NaN        NaN
 19        NaN        NaN        NaN
 20        NaN        NaN        NaN  ,
       IFRS(별도) Net Quarter                                                  \
       IFRS(별도)     2023/09     2023/12     2024/03     2024/06     2024/09
 0          매출액   458662.00   426101.00   512396.00   537341.00   558289.00
 1         영업이익   -21680.00   -17514.00    20074.00    72225.00    45049.00
 2   영업이익(발표기준)   -21680.00   -17514.00    20074.00    72225.00    45049.00
 3        당기순이익   104168.00    12376.00    97374.00    70984.00    56946.00
 4         자산총계  2944904.00  2968573.00  3120833.00  3176354.00  3233828.00
 5         부채총계   682824.00   720695.00   799438.00   807647.00   833108.00
 6         자본총계  2262080.00  2247878.00  2321395.00  2368707.00  2400720.00
 7          자본금     8975.00     8975.00     8975.00     8975.00     8975.00
 8         부채비율       30.19       32.06       34.44       34.10       34.70
 9          유보율    25103.84    24945.60    25764.72    26291.87    26648.55
 10       영업이익률       -4.73       -4.11        3.92       13.44        8.07
 11        순이익률       22.71        2.90       19.00       13.21       10.20
 12         ROA       14.36        1.67       12.79        9.02        7.11
 13         ROE       18.75        2.20       17.05       12.11        9.55
 14      EPS(원)     1534.00      182.00     1434.00     1045.00      838.00
 15      BPS(원)    33302.00    33093.00    34175.00    34872.00    35343.00
 16      DPS(원)      361.00      361.00      361.00      361.00      361.00
 17         PER         NaN         NaN         NaN         NaN         NaN
 18         PBR        2.05        2.37        2.41        2.34        1.74
 19       발행주식수  5969783.00  5969783.00  5969783.00  5969783.00  5969783.00
 20       배당수익률        0.53        0.46        0.44        0.44        0.59


    2024/12(E) 2025/03(E) 2025/06(E)
 0         NaN        NaN        NaN
 1         NaN        NaN        NaN
 2         NaN        NaN        NaN
 3         NaN        NaN        NaN

## load from CSV

In [6]:
pd.read_csv('../datasets/02.magic.csv')

     code    name    ROIC  EV/EBITDA
0  187660  에디엠코리아  2110.7       0.02
1  227420   도부마스크   394.7       1.23
2  225220    제놀루션   333.9       2.40
3    1880    DL건설   344.8       3.15

## load from html

In [7]:
import requests

uri = 'https://finance.naver.com/'
requests.get(uri)

response = requests.get(uri)

In [8]:
df_read_html = pd.read_html(io=response.text, encoding='utf-8')

/tmp/ipykernel_579/3376660858.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_read_html = pd.read_html(io=response.text, encoding='utf-8')

In [9]:
type(df_read_html), len(df_read_html)

(list, 12)

In [10]:
df_read_html[0]

                  종목명   현재가    전일대비      등락률
0                대원전선  3425  상승 215   +6.70%
1              오리엔트정공  6350  하락 350   -5.22%
2    KODEX 200선물인버스2X  2470   상승 30   +1.23%
3               SG글로벌  3960  상승 695  +21.29%
4               넥스트아이   606   상승 10   +1.68%
5               쓰리빌리언  6750  상승 750  +12.50%
6             오리엔트바이오  1211   상승 51   +4.40%
7   KODEX 코스닥150선물인버스  4090   상승 40   +0.99%
8    KODEX 코스닥150레버리지  6955  하락 125   -1.77%
9           코오롱모빌리티그룹  2980  상승 455  +18.02%
10          이스트아시아홀딩스    63    하락 6   -8.70%
11          한국ANKOR유전   342   상승 16   +4.91%
12                유비온  1336   상승 64   +5.03%
13               삼부토건   993   상승 26   +2.69%
14           에이비프로바이오   486   하락 35   -6.72%

In [11]:
df_read_html[1]

           종목명    현재가       전일대비      등락률
0       한국정밀기계   2925    상한가 675  +30.00%
1       아이윈플러스    963    상한가 222  +29.96%
2        인벤티지랩  17350  상한가 4,000  +29.96%
3        GH신소재   3450    상한가 795  +29.94%
4      뱅크웨어글로벌   9420  상한가 2,170  +29.93%
5      CJ씨푸드1우  23650  상한가 5,420  +29.73%
6        효성오앤비   9370   상승 1,890  +25.27%
7        대원전선우   4745     상승 925  +24.21%
8      자람테크놀로지  48550   상승 8,550  +21.38%
9        SG글로벌   3960     상승 695  +21.29%
10   코오롱모빌리티그룹   2980     상승 455  +18.02%
11       에이직랜드  31300   상승 4,300  +15.93%
12  코오롱모빌리티그룹우   4560     상승 615  +15.59%
13         나이벡  17920   상승 2,260  +14.43%
14   엔브이에이치코리아   2800     상승 345  +14.05%

## save to file

In [12]:
df_up_cds = df_read_html[1]
df_up_cds

           종목명    현재가       전일대비      등락률
0       한국정밀기계   2925    상한가 675  +30.00%
1       아이윈플러스    963    상한가 222  +29.96%
2        인벤티지랩  17350  상한가 4,000  +29.96%
3        GH신소재   3450    상한가 795  +29.94%
4      뱅크웨어글로벌   9420  상한가 2,170  +29.93%
5      CJ씨푸드1우  23650  상한가 5,420  +29.73%
6        효성오앤비   9370   상승 1,890  +25.27%
7        대원전선우   4745     상승 925  +24.21%
8      자람테크놀로지  48550   상승 8,550  +21.38%
9        SG글로벌   3960     상승 695  +21.29%
10   코오롱모빌리티그룹   2980     상승 455  +18.02%
11       에이직랜드  31300   상승 4,300  +15.93%
12  코오롱모빌리티그룹우   4560     상승 615  +15.59%
13         나이벡  17920   상승 2,260  +14.43%
14   엔브이에이치코리아   2800     상승 345  +14.05%

In [13]:
df_up_cds.to_csv('../datasets/02.save_html.csv')

In [14]:
type(df_up_cds), len(df_up_cds)

(pandas.core.frame.DataFrame, 15)

In [15]:
file_path = '../datasets/test.xlsx'
pd.read_excel(file_path, header=2)

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고
0,유진투자증권,/img/sub/ico_xls.gif,2012/10/08,50만원,변경전,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,NaN
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.00000,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN
2,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경율,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,SK증권,/img/sub/ico_xls.gif,2011/11/18,50만원,변경전,2500.00000,1750.0,1250.0,250.0,2500.0,75.0,1250.0,250.0,NaN
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.00000,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경율,-0.23077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN
93,비엔케이투자증권,/img/sub/ico_pdf.gif,2016/12/05,50만원,변경전,NaN,NaN,NaN,750.0,NaN,NaN,NaN,750.0,NaN
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.00000,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN
95,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경율,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN

In [16]:
findPostInterates = pd.read_excel(file_path, header=2)
findPostInterates

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고
0,유진투자증권,/img/sub/ico_xls.gif,2012/10/08,50만원,변경전,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,NaN
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.00000,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN
2,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경율,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,SK증권,/img/sub/ico_xls.gif,2011/11/18,50만원,변경전,2500.00000,1750.0,1250.0,250.0,2500.0,75.0,1250.0,250.0,NaN
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.00000,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경율,-0.23077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN
93,비엔케이투자증권,/img/sub/ico_pdf.gif,2016/12/05,50만원,변경전,NaN,NaN,NaN,750.0,NaN,NaN,NaN,750.0,NaN
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.00000,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN
95,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경율,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN

In [17]:
changedInterates = findPostInterates[findPostInterates['구분'] == '변경후']
changedInterates

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.0,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.0,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경
7,유안타증권,/img/sub/ico_pdf.gif,2021/01/04,50만원,변경후,2500.0,1750.0,985.0,500.0,2500.0,70.0,985.0,500.0,NaN
10,신한투자증권,/img/sub/ico_pdf.gif,2015/04/01,50만원,변경후,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,유화증권,/img/sub/ico_pdf.gif,2012/05/02,50만원,변경후,2490.0,390.0,1240.0,NaN,2490.0,390.0,1240.0,NaN,증권유관기관 수수료인하('12.5.2)부분 반영
16,미래에셋증권,/img/sub/ico_pdf.gif,2017/01/02,50만원,변경후,2450.0,700.0,700.0,700.0,2450.0,70.0,70.0,70.0,NaN
18,상상인증권,/img/sub/ico_pdf.gif,2020/04/23,50만원,변경후,2450.0,700.0,1000.0,700.0,2450.0,700.0,1000.0,700.0,NaN
20,대신증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2486.0,1536.0,986.0,986.0,2486.0,1536.0,986.0,986.0,NaN
23,교보증권,/img/sub/ico_pdf.gif,2021/09/01,50만원,변경후,2490.0,1240.0,1240.0,1240.0,2490.0,1240.0,1240.0,1240.0,NaN
25,NH투자증권,/img/sub/ico_pdf.gif,2020/06/10,50만원,변경후,2486.0,1571.0,1486.0,1486.0,2486.0,1571.0,1486.0,1486.0,NAMUH 50
27,한양증권,/img/sub/ico_hwp.gif,2012/10/12,50만원,변경후,2487.0,2236.0,996.0,500.0,2487.0,2236.0,996.0,500.0,NaN
30,신영증권,/img/sub/ico_hwp.gif,2021/08/23,50만원,변경후,2246.0,496.0,1246.0,496.0,2246.0,496.0,1246.0,496.0,NaN
33,삼성증권,/img/sub/ico_pdf.gif,2021/10/01,50만원,변경후,2486.0,2236.0,1236.0,2236.0,2486.0,2236.0,1236.0,2236.0,NaN
36,메리츠증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2490.0,1890.0,990.0,1890.0,2490.0,1890.0,990.0,1890.0,NaN
39,KB증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2487.0,1786.0,1237.0,987.0,2487.0,75.0,750.0,600.0,NaN
42,한화투자증권,/img/sub/ico_pdf.gif,2016/05/30,50만원,변경후,2480.0,2480.0,980.0,750.0,2480.0,2480.0,980.0,750.0,NaN
44,현대차증권,/img/sub/ico_xlsx.gif,2011/11/07,50만원,변경후,2491.0,2291.0,1241.0,991.0,2491.0,2291.0,1241.0,991.0,NaN
46,DB금융투자,/img/sub/ico_doc.gif,2015/01/02,50만원,변경후,2496.0,1246.0,1246.0,1246.0,2496.0,1246.0,1246.0,1246.0,NaN
49,아이엠증권,/img/sub/ico_hwp.gif,2012/05/02,50만원,변경후,2486.0,1686.0,1236.0,1686.0,2486.0,1686.0,1236.0,1686.0,유관수수료인하
51,부국증권,/img/sub/ico_hwp.gif,2011/11/18,50만원,변경후,2227.0,477.0,977.0,750.0,2227.0,477.0,977.0,750.0,NaN
53,한국투자증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2486.0,2636.0,1236.0,2636.0,NaN,70.0,1236.0,70.0,코스피/코스닥/장외단주/코넥스
56,하나증권,/img/sub/ico_pdf.gif,2014/09/01,50만원,변경후,2480.0,2480.0,2480.0,2480.0,2480.0,70.0,70.0,70.0,NaN
59,리딩투자증권,/img/sub/ico_pdf.gif,2014/07/14,50만원,변경후,2500.0,120.0,700.0,NaN,2500.0,120.0,700.0,NaN,NaN
62,키움증권,/img/sub/ico_pdf.gif,2020/12/31,50만원,변경후,1500.0,70.0,750.0,70.0,1500.0,70.0,750.0,70.0,NaN
65,엘에스증권,/img/sub/ico_pdf.gif,2012/12/03,50만원,변경후,2400.0,75.0,500.0,75.0,1500.0,75.0,500.0,75.0,거래금액 5천만원 미만 : 0.48%\n거래금액 5천~3억 미만 : 0.45%\n거...
67,도이치증권,/img/sub/ico_pdf.gif,2014/12/17,50만원,변경후,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,코리아에셋투자증권,/img/sub/ico_pdf.gif,2019/04/10,50만원,변경후,500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,흥국증권,/img/sub/ico_pdf.gif,2012/06/01,50만원,변경후,2450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,IBK투자증권,/img/sub/ico_hwp.gif,2013/02/04,50만원,변경후,2500.0,500.0,1250.0,500.0,2500.0,500.0,1250.0,500.0,NaN
78,케이프투자증권,/img/sub/ico_doc.gif,2015/04/20,50만원,변경후,3750.0,2500.0,NaN,450.0,3750.0,75.0,NaN,75.0,1. 고객등급 실버등급은 당일 종목당 매수/매도 매체별 합산 하여 50만원 미만시 ...
81,DS투자증권,/img/sub/ico_hwp.gif,2021/01/01,50만원,변경후,2478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,다올투자증권,/img/sub/ico_pdf.gif,2018/03/12,50만원,변경후,2490.0,70.0,750.0,70.0,2490.0,70.0,750.0,70.0,NaN
87,카카오페이증권,/img/sub/ico_pdf.gif,2024/10/14,50만원,변경후,2500.0,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN
90,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경후,1500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.0,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN

In [18]:
changedInterates['증권사 개설 계좌'] = changedInterates['HTS'] + changedInterates['스마트폰']
changedInterates

/tmp/ipykernel_579/1000570393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  changedInterates['증권사 개설 계좌'] = changedInterates['HTS'] + changedInterates['스마트폰']

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고,증권사 개설 계좌
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.0,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN,1650.0
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.0,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경,3500.0
7,유안타증권,/img/sub/ico_pdf.gif,2021/01/04,50만원,변경후,2500.0,1750.0,985.0,500.0,2500.0,70.0,985.0,500.0,NaN,2250.0
10,신한투자증권,/img/sub/ico_pdf.gif,2015/04/01,50만원,변경후,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,유화증권,/img/sub/ico_pdf.gif,2012/05/02,50만원,변경후,2490.0,390.0,1240.0,NaN,2490.0,390.0,1240.0,NaN,증권유관기관 수수료인하('12.5.2)부분 반영,NaN
16,미래에셋증권,/img/sub/ico_pdf.gif,2017/01/02,50만원,변경후,2450.0,700.0,700.0,700.0,2450.0,70.0,70.0,70.0,NaN,1400.0
18,상상인증권,/img/sub/ico_pdf.gif,2020/04/23,50만원,변경후,2450.0,700.0,1000.0,700.0,2450.0,700.0,1000.0,700.0,NaN,1400.0
20,대신증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2486.0,1536.0,986.0,986.0,2486.0,1536.0,986.0,986.0,NaN,2522.0
23,교보증권,/img/sub/ico_pdf.gif,2021/09/01,50만원,변경후,2490.0,1240.0,1240.0,1240.0,2490.0,1240.0,1240.0,1240.0,NaN,2480.0
25,NH투자증권,/img/sub/ico_pdf.gif,2020/06/10,50만원,변경후,2486.0,1571.0,1486.0,1486.0,2486.0,1571.0,1486.0,1486.0,NAMUH 50,3057.0
27,한양증권,/img/sub/ico_hwp.gif,2012/10/12,50만원,변경후,2487.0,2236.0,996.0,500.0,2487.0,2236.0,996.0,500.0,NaN,2736.0
30,신영증권,/img/sub/ico_hwp.gif,2021/08/23,50만원,변경후,2246.0,496.0,1246.0,496.0,2246.0,496.0,1246.0,496.0,NaN,992.0
33,삼성증권,/img/sub/ico_pdf.gif,2021/10/01,50만원,변경후,2486.0,2236.0,1236.0,2236.0,2486.0,2236.0,1236.0,2236.0,NaN,4472.0
36,메리츠증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2490.0,1890.0,990.0,1890.0,2490.0,1890.0,990.0,1890.0,NaN,3780.0
39,KB증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2487.0,1786.0,1237.0,987.0,2487.0,75.0,750.0,600.0,NaN,2773.0
42,한화투자증권,/img/sub/ico_pdf.gif,2016/05/30,50만원,변경후,2480.0,2480.0,980.0,750.0,2480.0,2480.0,980.0,750.0,NaN,3230.0
44,현대차증권,/img/sub/ico_xlsx.gif,2011/11/07,50만원,변경후,2491.0,2291.0,1241.0,991.0,2491.0,2291.0,1241.0,991.0,NaN,3282.0
46,DB금융투자,/img/sub/ico_doc.gif,2015/01/02,50만원,변경후,2496.0,1246.0,1246.0,1246.0,2496.0,1246.0,1246.0,1246.0,NaN,2492.0
49,아이엠증권,/img/sub/ico_hwp.gif,2012/05/02,50만원,변경후,2486.0,1686.0,1236.0,1686.0,2486.0,1686.0,1236.0,1686.0,유관수수료인하,3372.0
51,부국증권,/img/sub/ico_hwp.gif,2011/11/18,50만원,변경후,2227.0,477.0,977.0,750.0,2227.0,477.0,977.0,750.0,NaN,1227.0
53,한국투자증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2486.0,2636.0,1236.0,2636.0,NaN,70.0,1236.0,70.0,코스피/코스닥/장외단주/코넥스,5272.0
56,하나증권,/img/sub/ico_pdf.gif,2014/09/01,50만원,변경후,2480.0,2480.0,2480.0,2480.0,2480.0,70.0,70.0,70.0,NaN,4960.0
59,리딩투자증권,/img/sub/ico_pdf.gif,2014/07/14,50만원,변경후,2500.0,120.0,700.0,NaN,2500.0,120.0,700.0,NaN,NaN,NaN
62,키움증권,/img/sub/ico_pdf.gif,2020/12/31,50만원,변경후,1500.0,70.0,750.0,70.0,1500.0,70.0,750.0,70.0,NaN,140.0
65,엘에스증권,/img/sub/ico_pdf.gif,2012/12/03,50만원,변경후,2400.0,75.0,500.0,75.0,1500.0,75.0,500.0,75.0,거래금액 5천만원 미만 : 0.48%\n거래금액 5천~3억 미만 : 0.45%\n거...,150.0
67,도이치증권,/img/sub/ico_pdf.gif,2014/12/17,50만원,변경후,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,코리아에셋투자증권,/img/sub/ico_pdf.gif,2019/04/10,50만원,변경후,500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,흥국증권,/img/sub/ico_pdf.gif,2012/06/01,50만원,변경후,2450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,IBK투자증권,/img/sub/ico_hwp.gif,2013/02/04,50만원,변경후,2500.0,500.0,1250.0,500.0,2500.0,500.0,1250.0,500.0,NaN,1000.0
78,케이프투자증권,/img/sub/ico_doc.gif,2015/04/20,50만원,변경후,3750.0,2500.0,NaN,450.0,3750.0,75.0,NaN,75.0,1. 고객등급 실버등급은 당일 종목당 매수/매도 매체별 합산 하여 50만원 미만시 ...,2950.0
81,DS투자증권,/img/sub/ico_hwp.gif,2021/01/01,50만원,변경후,2478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,다올투자증권,/img/sub/ico_pdf.gif,2018/03/12,50만원,변경후,2490.0,70.0,750.0,70.0,2490.0,70.0,750.0,70.0,NaN,140.0
87,카카오페이증권,/img/sub/ico_pdf.gif,2024/10/14,50만원,변경후,2500.0,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN
90,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경후,1500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.0,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN,2246.0